[package]
name = "krustyboard"
version = "1.4.5"
authors = ["yakrider <yakrider@gmail.com>"]
description = "Keyboard Remapping to support layer-2 and layer-3 functionality."
documentation = "https://docs.rs/krustyboard"
homepage = "https://github.com/yakrider/krustyboard"
repository = "https://github.com/yakrider/krustyboard"
readme = "README.md"
keywords = ["hotkey", "autohotkey", "mouse", "keyboard", "shortcuts"]
categories = ["api-bindings"]
license = "MIT"
edition = "2021"
build = "build.rs"


[[bin]]
name = "krustyboard"
path = "src/bin/krustyboard/krustyboard.rs"


[build-dependencies]
winres = "0.1"

[package.metadata.winres]
OriginalFilename = "krustyboard.exe"
ProductName = "KrustyBoard"


[dependencies]
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
derivative = "2.2"
once_cell = "1.9"
atomic_refcell = "0.1"
brightness = "0.5"
async-trait = "0.1"
futures = "0.3"
rand = "0.8"
itertools = "0.12"
rustc-hash = "1.1"
derive_deref = "1.1"
base64 = "0.21"
image = "0.24"
tray-icon = "0.13"
tao = "0.27"

[target.'cfg(windows)'.dependencies.windows]
version = "0.44"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Accessibility",
    "Win32_System_SystemServices",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
    "Win32_Graphics_Dwm",
    "Win32_UI_HiDpi",
]



# enable when profiling (e.g with FlameGraph)
#[profile.release]
#debug = true



[lints.clippy]
erasing_op             = "warn"
missing_safety_doc     = "allow"
manual_non_exhaustive  = "allow"
new_without_default    = "allow"
upper_case_acronyms    = "allow"
blocks_in_conditions   = "allow"
needless_else          = "allow"
collapsible_if         = "allow"
collapsible_else_if    = "allow"

